version: 0.0
os: linux
files:
  - source: /
    destination: /home/code-build/shark-nodejs
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 100
      runas: root
