version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/docker
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/after.sh
      timeout: 60
      runas: root
