  
### appspec.yml ####
version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/dockernodejs/docker
permissions:
  - object: /tmp/dockernodejs
    owner: kk
    group: kk
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 120
      runas: kk
  AfterInstall:
    - location: scripts/after.sh
      timeout: 120
      runas: kk
