  
### appspec.yml ####
version: 0.0
os: linux
files:
  - source: /
    destination: /home/kalyan/dockernodejs
permissions:
  - object: /home/kalyan
    owner: kalyan
    group: kalyan
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 120
      runas: kalyan
  AfterInstall:
    - location: scripts/after.sh
      timeout: 120
      runas: kalyan
