version: 0.2

phases:
  install:
    commands:
      - sudo yum install -y docker
      - sudo systemctl enable docker
      - sudo systemctl restart docker
  pre-build:
    commands:
      - docker build -t dockernodes/shark .
  build:
    commands:
      - docker images
      - docker run -d -p 8080:8080 dockernodes/shark 
# Include only the files required for your application to run.
#artifacts:
  #files:
    #- '**/*'
