version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    container_name: node-api
    #volumes:
     #  - ./api:/usr/src/app/api
      # - /usr/src/app/api/node_modules